# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- task: NodeTool@0
  displayName: Install Node.js
  inputs:
    versionSpec: '12.x'
- task: Npm@1
  displayName: Install Angular
  inputs:
    command: 'custom'
    workingDir: 'BookClubClient'
    customCommand: 'install -g @angular/cli@latest'
- task: Npm@1
  displayName: Npm Install
  inputs:
    command: 'install'
    workingDir: 'BookClubClient'
- task: Npm@1
  displayName: Npm Build
  inputs:
    command: 'custom'
    workingDir: 'BookClubClient'
    customCommand: 'run build --prod'
- task: AzureRmWebAppDeployment@4
  displayName: Azure Deploy
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(b5a73573-c365-4df4-90d9-79329c2413a9)'
    appType: 'webAppLinux'
    WebAppName: 'BookClub'
    package: ./BookClubClient/dist/BookClubClient
    RuntimeStack: 'NODE|12-lts'