# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: Install Node.js
  inputs:
    versionSpec: '14.x'
- task: Npm@1
  displayName: Install Angular CLI
  inputs:
    command: 'custom'
    customCommand: 'install @angular-cli'
- task: Npm@1
  displayName: Install Project
  inputs:
    command: 'install'
    workingDir: '**/BookClubClient'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(b5a73573-c365-4df4-90d9-79329c2413a9)'
    appType: 'webAppLinux'
    WebAppName: 'BookClub'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'